import Foundation
import CoreGraphics
func check(_ value: @autoclosure () -> Bool, _ name: String) { if !value() { fatalError(name) }; print("PASS \(name)") }
var flow = CrossroadsFlow()
check(CrossroadsFlow.display(size:CGSize(width:900,height:650),horizontalDivision:true,activeDivision:true,hingeKnown:true,hingeClosed:false,sawDivision:true) == .inside, "wide window with horizontal hinge remains stacked inside")
check(CrossroadsFlow.display(size:CGSize(width:650,height:900),horizontalDivision:false,activeDivision:true,hingeKnown:true,hingeClosed:true,sawDivision:true) == .unknown, "unsupported active division cannot become outside")
check(CrossroadsFlow.display(size:CGSize(width:400,height:800),horizontalDivision:false,activeDivision:false,hingeKnown:true,hingeClosed:true,sawDivision:true) == .outside, "closed hinge without inner division becomes outside")
check(CrossroadsFlow.display(size:CGSize(width:400,height:800),horizontalDivision:false,activeDivision:false,hingeKnown:true,hingeClosed:false,sawDivision:true) == .unknown, "resize alone does not become outside")
check(!flow.updateDisplay(.outside, active: true), "closing before placement cannot drop")
flow.updateDisplay(.inside, active: true)
flow.park(offset: CGPoint(x:0.2,y:-0.1))
check(flow.placement == CGPoint(x:0.2,y:-0.1), "capture real placement")
flow.park(offset: CGPoint(x:0.8,y:0.8))
check(flow.placement == CGPoint(x:0.2,y:-0.1), "placement immutable")
check(!flow.updateDisplay(.unknown, active:true), "unknown transition cannot drop")
check(!flow.updateDisplay(.outside, active:false), "inactive outside cannot drop")
check(!flow.updateDisplay(.outside, active:true, renderReady:false), "unmounted outer renderer cannot drop")
check(flow.updateDisplay(.outside, active:true, renderReady:true), "outside activation releases")
check(!flow.updateDisplay(.outside, active:true, renderReady:true), "cannot release twice")
flow.updateDisplay(.inside, active:true)
check(!flow.updateDisplay(.outside, active:true, renderReady:true), "reopening cannot release twice")
flow.reset()
check(flow.placement == nil && !flow.released, "retry clears placement")
flow.park(offset: .zero)
check(flow.placement == nil, "cannot park outside")
flow.updateDisplay(.inside, active:true)
flow.park(offset: .zero)
check(flow.updateDisplay(.outside, active:true, renderReady:true), "second attempt releases")
var dwell = ParkDwell()
for _ in 0..<20 { _ = dwell.step(distance:5,speed:0,delta:1.0/60,fresh:true) }
check(!dwell.ready, "short stop is not parked")
_ = dwell.step(distance:5,speed:9,delta:1.0/60,fresh:true)
check(dwell.elapsed == 0, "moving resets dwell")
for _ in 0..<40 { _ = dwell.step(distance:5,speed:0,delta:1.0/60,fresh:false) }
check(!dwell.ready, "stale source cannot park")
for _ in 0..<40 { _ = dwell.step(distance:5,speed:0,delta:1.0/60,fresh:true) }
check(dwell.ready, "steady target parks")
_ = dwell.step(distance:21,speed:0,delta:1.0/60,fresh:true)
check(!dwell.ready, "leaving target resets dwell")
